// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_msg_2eproto__INCLUDED
#define PROTOBUF_msg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_2eproto();
void protobuf_AssignDesc_msg_2eproto();
void protobuf_ShutdownFile_msg_2eproto();

class MSG;
class MSG_T;

// ===================================================================

class MSG_T : public ::google::protobuf::Message {
 public:
  MSG_T();
  virtual ~MSG_T();

  MSG_T(const MSG_T& from);

  inline MSG_T& operator=(const MSG_T& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_T& default_instance();

  void Swap(MSG_T* other);

  // implements Message ----------------------------------------------

  MSG_T* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_T& from);
  void MergeFrom(const MSG_T& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool bool_optional = 1;
  inline bool has_bool_optional() const;
  inline void clear_bool_optional();
  static const int kBoolOptionalFieldNumber = 1;
  inline bool bool_optional() const;
  inline void set_bool_optional(bool value);

  // required bool bool_required = 2;
  inline bool has_bool_required() const;
  inline void clear_bool_required();
  static const int kBoolRequiredFieldNumber = 2;
  inline bool bool_required() const;
  inline void set_bool_required(bool value);

  // repeated bool bool_repeated = 3;
  inline int bool_repeated_size() const;
  inline void clear_bool_repeated();
  static const int kBoolRepeatedFieldNumber = 3;
  inline bool bool_repeated(int index) const;
  inline void set_bool_repeated(int index, bool value);
  inline void add_bool_repeated(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      bool_repeated() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_bool_repeated();

  // optional int32 int_optional = 4;
  inline bool has_int_optional() const;
  inline void clear_int_optional();
  static const int kIntOptionalFieldNumber = 4;
  inline ::google::protobuf::int32 int_optional() const;
  inline void set_int_optional(::google::protobuf::int32 value);

  // required int32 int_required = 5;
  inline bool has_int_required() const;
  inline void clear_int_required();
  static const int kIntRequiredFieldNumber = 5;
  inline ::google::protobuf::int32 int_required() const;
  inline void set_int_required(::google::protobuf::int32 value);

  // repeated int32 int_repeated = 6;
  inline int int_repeated_size() const;
  inline void clear_int_repeated();
  static const int kIntRepeatedFieldNumber = 6;
  inline ::google::protobuf::int32 int_repeated(int index) const;
  inline void set_int_repeated(int index, ::google::protobuf::int32 value);
  inline void add_int_repeated(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      int_repeated() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_int_repeated();

  // optional int64 int64_optional = 7;
  inline bool has_int64_optional() const;
  inline void clear_int64_optional();
  static const int kInt64OptionalFieldNumber = 7;
  inline ::google::protobuf::int64 int64_optional() const;
  inline void set_int64_optional(::google::protobuf::int64 value);

  // required int64 int64_required = 8;
  inline bool has_int64_required() const;
  inline void clear_int64_required();
  static const int kInt64RequiredFieldNumber = 8;
  inline ::google::protobuf::int64 int64_required() const;
  inline void set_int64_required(::google::protobuf::int64 value);

  // repeated int64 int64_repeated = 9;
  inline int int64_repeated_size() const;
  inline void clear_int64_repeated();
  static const int kInt64RepeatedFieldNumber = 9;
  inline ::google::protobuf::int64 int64_repeated(int index) const;
  inline void set_int64_repeated(int index, ::google::protobuf::int64 value);
  inline void add_int64_repeated(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      int64_repeated() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_int64_repeated();

  // optional string string_optional = 10;
  inline bool has_string_optional() const;
  inline void clear_string_optional();
  static const int kStringOptionalFieldNumber = 10;
  inline const ::std::string& string_optional() const;
  inline void set_string_optional(const ::std::string& value);
  inline void set_string_optional(const char* value);
  inline void set_string_optional(const char* value, size_t size);
  inline ::std::string* mutable_string_optional();
  inline ::std::string* release_string_optional();
  inline void set_allocated_string_optional(::std::string* string_optional);

  // required string string_required = 11;
  inline bool has_string_required() const;
  inline void clear_string_required();
  static const int kStringRequiredFieldNumber = 11;
  inline const ::std::string& string_required() const;
  inline void set_string_required(const ::std::string& value);
  inline void set_string_required(const char* value);
  inline void set_string_required(const char* value, size_t size);
  inline ::std::string* mutable_string_required();
  inline ::std::string* release_string_required();
  inline void set_allocated_string_required(::std::string* string_required);

  // repeated string string_repeated = 12;
  inline int string_repeated_size() const;
  inline void clear_string_repeated();
  static const int kStringRepeatedFieldNumber = 12;
  inline const ::std::string& string_repeated(int index) const;
  inline ::std::string* mutable_string_repeated(int index);
  inline void set_string_repeated(int index, const ::std::string& value);
  inline void set_string_repeated(int index, const char* value);
  inline void set_string_repeated(int index, const char* value, size_t size);
  inline ::std::string* add_string_repeated();
  inline void add_string_repeated(const ::std::string& value);
  inline void add_string_repeated(const char* value);
  inline void add_string_repeated(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& string_repeated() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_string_repeated();

  // @@protoc_insertion_point(class_scope:MSG.T)
 private:
  inline void set_has_bool_optional();
  inline void clear_has_bool_optional();
  inline void set_has_bool_required();
  inline void clear_has_bool_required();
  inline void set_has_int_optional();
  inline void clear_has_int_optional();
  inline void set_has_int_required();
  inline void clear_has_int_required();
  inline void set_has_int64_optional();
  inline void clear_has_int64_optional();
  inline void set_has_int64_required();
  inline void clear_has_int64_required();
  inline void set_has_string_optional();
  inline void clear_has_string_optional();
  inline void set_has_string_required();
  inline void clear_has_string_required();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool bool_optional_;
  bool bool_required_;
  ::google::protobuf::int32 int_optional_;
  ::google::protobuf::RepeatedField< bool > bool_repeated_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > int_repeated_;
  ::google::protobuf::int64 int64_optional_;
  ::google::protobuf::int64 int64_required_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > int64_repeated_;
  ::std::string* string_optional_;
  ::std::string* string_required_;
  ::google::protobuf::RepeatedPtrField< ::std::string> string_repeated_;
  ::google::protobuf::int32 int_required_;
  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static MSG_T* default_instance_;
};
// -------------------------------------------------------------------

class MSG : public ::google::protobuf::Message {
 public:
  MSG();
  virtual ~MSG();

  MSG(const MSG& from);

  inline MSG& operator=(const MSG& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG& default_instance();

  void Swap(MSG* other);

  // implements Message ----------------------------------------------

  MSG* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG& from);
  void MergeFrom(const MSG& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MSG_T T;

  // accessors -------------------------------------------------------

  // optional bool bool_optional = 1;
  inline bool has_bool_optional() const;
  inline void clear_bool_optional();
  static const int kBoolOptionalFieldNumber = 1;
  inline bool bool_optional() const;
  inline void set_bool_optional(bool value);

  // required bool bool_required = 2;
  inline bool has_bool_required() const;
  inline void clear_bool_required();
  static const int kBoolRequiredFieldNumber = 2;
  inline bool bool_required() const;
  inline void set_bool_required(bool value);

  // repeated bool bool_repeated = 3;
  inline int bool_repeated_size() const;
  inline void clear_bool_repeated();
  static const int kBoolRepeatedFieldNumber = 3;
  inline bool bool_repeated(int index) const;
  inline void set_bool_repeated(int index, bool value);
  inline void add_bool_repeated(bool value);
  inline const ::google::protobuf::RepeatedField< bool >&
      bool_repeated() const;
  inline ::google::protobuf::RepeatedField< bool >*
      mutable_bool_repeated();

  // optional int32 int_optional = 4;
  inline bool has_int_optional() const;
  inline void clear_int_optional();
  static const int kIntOptionalFieldNumber = 4;
  inline ::google::protobuf::int32 int_optional() const;
  inline void set_int_optional(::google::protobuf::int32 value);

  // required int32 int_required = 5;
  inline bool has_int_required() const;
  inline void clear_int_required();
  static const int kIntRequiredFieldNumber = 5;
  inline ::google::protobuf::int32 int_required() const;
  inline void set_int_required(::google::protobuf::int32 value);

  // repeated int32 int_repeated = 6;
  inline int int_repeated_size() const;
  inline void clear_int_repeated();
  static const int kIntRepeatedFieldNumber = 6;
  inline ::google::protobuf::int32 int_repeated(int index) const;
  inline void set_int_repeated(int index, ::google::protobuf::int32 value);
  inline void add_int_repeated(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      int_repeated() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_int_repeated();

  // optional int64 int64_optional = 7;
  inline bool has_int64_optional() const;
  inline void clear_int64_optional();
  static const int kInt64OptionalFieldNumber = 7;
  inline ::google::protobuf::int64 int64_optional() const;
  inline void set_int64_optional(::google::protobuf::int64 value);

  // required int64 int64_required = 8;
  inline bool has_int64_required() const;
  inline void clear_int64_required();
  static const int kInt64RequiredFieldNumber = 8;
  inline ::google::protobuf::int64 int64_required() const;
  inline void set_int64_required(::google::protobuf::int64 value);

  // repeated int64 int64_repeated = 9;
  inline int int64_repeated_size() const;
  inline void clear_int64_repeated();
  static const int kInt64RepeatedFieldNumber = 9;
  inline ::google::protobuf::int64 int64_repeated(int index) const;
  inline void set_int64_repeated(int index, ::google::protobuf::int64 value);
  inline void add_int64_repeated(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      int64_repeated() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_int64_repeated();

  // optional string string_optional = 10;
  inline bool has_string_optional() const;
  inline void clear_string_optional();
  static const int kStringOptionalFieldNumber = 10;
  inline const ::std::string& string_optional() const;
  inline void set_string_optional(const ::std::string& value);
  inline void set_string_optional(const char* value);
  inline void set_string_optional(const char* value, size_t size);
  inline ::std::string* mutable_string_optional();
  inline ::std::string* release_string_optional();
  inline void set_allocated_string_optional(::std::string* string_optional);

  // required string string_required = 11;
  inline bool has_string_required() const;
  inline void clear_string_required();
  static const int kStringRequiredFieldNumber = 11;
  inline const ::std::string& string_required() const;
  inline void set_string_required(const ::std::string& value);
  inline void set_string_required(const char* value);
  inline void set_string_required(const char* value, size_t size);
  inline ::std::string* mutable_string_required();
  inline ::std::string* release_string_required();
  inline void set_allocated_string_required(::std::string* string_required);

  // repeated string string_repeated = 12;
  inline int string_repeated_size() const;
  inline void clear_string_repeated();
  static const int kStringRepeatedFieldNumber = 12;
  inline const ::std::string& string_repeated(int index) const;
  inline ::std::string* mutable_string_repeated(int index);
  inline void set_string_repeated(int index, const ::std::string& value);
  inline void set_string_repeated(int index, const char* value);
  inline void set_string_repeated(int index, const char* value, size_t size);
  inline ::std::string* add_string_repeated();
  inline void add_string_repeated(const ::std::string& value);
  inline void add_string_repeated(const char* value);
  inline void add_string_repeated(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& string_repeated() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_string_repeated();

  // optional .MSG.T T_optional = 13;
  inline bool has_t_optional() const;
  inline void clear_t_optional();
  static const int kTOptionalFieldNumber = 13;
  inline const ::MSG_T& t_optional() const;
  inline ::MSG_T* mutable_t_optional();
  inline ::MSG_T* release_t_optional();
  inline void set_allocated_t_optional(::MSG_T* t_optional);

  // required .MSG.T T_required = 14;
  inline bool has_t_required() const;
  inline void clear_t_required();
  static const int kTRequiredFieldNumber = 14;
  inline const ::MSG_T& t_required() const;
  inline ::MSG_T* mutable_t_required();
  inline ::MSG_T* release_t_required();
  inline void set_allocated_t_required(::MSG_T* t_required);

  // repeated .MSG.T T_repeated = 15;
  inline int t_repeated_size() const;
  inline void clear_t_repeated();
  static const int kTRepeatedFieldNumber = 15;
  inline const ::MSG_T& t_repeated(int index) const;
  inline ::MSG_T* mutable_t_repeated(int index);
  inline ::MSG_T* add_t_repeated();
  inline const ::google::protobuf::RepeatedPtrField< ::MSG_T >&
      t_repeated() const;
  inline ::google::protobuf::RepeatedPtrField< ::MSG_T >*
      mutable_t_repeated();

  // @@protoc_insertion_point(class_scope:MSG)
 private:
  inline void set_has_bool_optional();
  inline void clear_has_bool_optional();
  inline void set_has_bool_required();
  inline void clear_has_bool_required();
  inline void set_has_int_optional();
  inline void clear_has_int_optional();
  inline void set_has_int_required();
  inline void clear_has_int_required();
  inline void set_has_int64_optional();
  inline void clear_has_int64_optional();
  inline void set_has_int64_required();
  inline void clear_has_int64_required();
  inline void set_has_string_optional();
  inline void clear_has_string_optional();
  inline void set_has_string_required();
  inline void clear_has_string_required();
  inline void set_has_t_optional();
  inline void clear_has_t_optional();
  inline void set_has_t_required();
  inline void clear_has_t_required();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool bool_optional_;
  bool bool_required_;
  ::google::protobuf::int32 int_optional_;
  ::google::protobuf::RepeatedField< bool > bool_repeated_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > int_repeated_;
  ::google::protobuf::int64 int64_optional_;
  ::google::protobuf::int64 int64_required_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > int64_repeated_;
  ::std::string* string_optional_;
  ::std::string* string_required_;
  ::google::protobuf::RepeatedPtrField< ::std::string> string_repeated_;
  ::MSG_T* t_optional_;
  ::MSG_T* t_required_;
  ::google::protobuf::RepeatedPtrField< ::MSG_T > t_repeated_;
  ::google::protobuf::int32 int_required_;
  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static MSG* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_T

// optional bool bool_optional = 1;
inline bool MSG_T::has_bool_optional() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_T::set_has_bool_optional() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_T::clear_has_bool_optional() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_T::clear_bool_optional() {
  bool_optional_ = false;
  clear_has_bool_optional();
}
inline bool MSG_T::bool_optional() const {
  // @@protoc_insertion_point(field_get:MSG.T.bool_optional)
  return bool_optional_;
}
inline void MSG_T::set_bool_optional(bool value) {
  set_has_bool_optional();
  bool_optional_ = value;
  // @@protoc_insertion_point(field_set:MSG.T.bool_optional)
}

// required bool bool_required = 2;
inline bool MSG_T::has_bool_required() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_T::set_has_bool_required() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_T::clear_has_bool_required() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_T::clear_bool_required() {
  bool_required_ = false;
  clear_has_bool_required();
}
inline bool MSG_T::bool_required() const {
  // @@protoc_insertion_point(field_get:MSG.T.bool_required)
  return bool_required_;
}
inline void MSG_T::set_bool_required(bool value) {
  set_has_bool_required();
  bool_required_ = value;
  // @@protoc_insertion_point(field_set:MSG.T.bool_required)
}

// repeated bool bool_repeated = 3;
inline int MSG_T::bool_repeated_size() const {
  return bool_repeated_.size();
}
inline void MSG_T::clear_bool_repeated() {
  bool_repeated_.Clear();
}
inline bool MSG_T::bool_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.T.bool_repeated)
  return bool_repeated_.Get(index);
}
inline void MSG_T::set_bool_repeated(int index, bool value) {
  bool_repeated_.Set(index, value);
  // @@protoc_insertion_point(field_set:MSG.T.bool_repeated)
}
inline void MSG_T::add_bool_repeated(bool value) {
  bool_repeated_.Add(value);
  // @@protoc_insertion_point(field_add:MSG.T.bool_repeated)
}
inline const ::google::protobuf::RepeatedField< bool >&
MSG_T::bool_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.T.bool_repeated)
  return bool_repeated_;
}
inline ::google::protobuf::RepeatedField< bool >*
MSG_T::mutable_bool_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.T.bool_repeated)
  return &bool_repeated_;
}

// optional int32 int_optional = 4;
inline bool MSG_T::has_int_optional() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MSG_T::set_has_int_optional() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MSG_T::clear_has_int_optional() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MSG_T::clear_int_optional() {
  int_optional_ = 0;
  clear_has_int_optional();
}
inline ::google::protobuf::int32 MSG_T::int_optional() const {
  // @@protoc_insertion_point(field_get:MSG.T.int_optional)
  return int_optional_;
}
inline void MSG_T::set_int_optional(::google::protobuf::int32 value) {
  set_has_int_optional();
  int_optional_ = value;
  // @@protoc_insertion_point(field_set:MSG.T.int_optional)
}

// required int32 int_required = 5;
inline bool MSG_T::has_int_required() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MSG_T::set_has_int_required() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MSG_T::clear_has_int_required() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MSG_T::clear_int_required() {
  int_required_ = 0;
  clear_has_int_required();
}
inline ::google::protobuf::int32 MSG_T::int_required() const {
  // @@protoc_insertion_point(field_get:MSG.T.int_required)
  return int_required_;
}
inline void MSG_T::set_int_required(::google::protobuf::int32 value) {
  set_has_int_required();
  int_required_ = value;
  // @@protoc_insertion_point(field_set:MSG.T.int_required)
}

// repeated int32 int_repeated = 6;
inline int MSG_T::int_repeated_size() const {
  return int_repeated_.size();
}
inline void MSG_T::clear_int_repeated() {
  int_repeated_.Clear();
}
inline ::google::protobuf::int32 MSG_T::int_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.T.int_repeated)
  return int_repeated_.Get(index);
}
inline void MSG_T::set_int_repeated(int index, ::google::protobuf::int32 value) {
  int_repeated_.Set(index, value);
  // @@protoc_insertion_point(field_set:MSG.T.int_repeated)
}
inline void MSG_T::add_int_repeated(::google::protobuf::int32 value) {
  int_repeated_.Add(value);
  // @@protoc_insertion_point(field_add:MSG.T.int_repeated)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MSG_T::int_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.T.int_repeated)
  return int_repeated_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MSG_T::mutable_int_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.T.int_repeated)
  return &int_repeated_;
}

// optional int64 int64_optional = 7;
inline bool MSG_T::has_int64_optional() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MSG_T::set_has_int64_optional() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MSG_T::clear_has_int64_optional() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MSG_T::clear_int64_optional() {
  int64_optional_ = GOOGLE_LONGLONG(0);
  clear_has_int64_optional();
}
inline ::google::protobuf::int64 MSG_T::int64_optional() const {
  // @@protoc_insertion_point(field_get:MSG.T.int64_optional)
  return int64_optional_;
}
inline void MSG_T::set_int64_optional(::google::protobuf::int64 value) {
  set_has_int64_optional();
  int64_optional_ = value;
  // @@protoc_insertion_point(field_set:MSG.T.int64_optional)
}

// required int64 int64_required = 8;
inline bool MSG_T::has_int64_required() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MSG_T::set_has_int64_required() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MSG_T::clear_has_int64_required() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MSG_T::clear_int64_required() {
  int64_required_ = GOOGLE_LONGLONG(0);
  clear_has_int64_required();
}
inline ::google::protobuf::int64 MSG_T::int64_required() const {
  // @@protoc_insertion_point(field_get:MSG.T.int64_required)
  return int64_required_;
}
inline void MSG_T::set_int64_required(::google::protobuf::int64 value) {
  set_has_int64_required();
  int64_required_ = value;
  // @@protoc_insertion_point(field_set:MSG.T.int64_required)
}

// repeated int64 int64_repeated = 9;
inline int MSG_T::int64_repeated_size() const {
  return int64_repeated_.size();
}
inline void MSG_T::clear_int64_repeated() {
  int64_repeated_.Clear();
}
inline ::google::protobuf::int64 MSG_T::int64_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.T.int64_repeated)
  return int64_repeated_.Get(index);
}
inline void MSG_T::set_int64_repeated(int index, ::google::protobuf::int64 value) {
  int64_repeated_.Set(index, value);
  // @@protoc_insertion_point(field_set:MSG.T.int64_repeated)
}
inline void MSG_T::add_int64_repeated(::google::protobuf::int64 value) {
  int64_repeated_.Add(value);
  // @@protoc_insertion_point(field_add:MSG.T.int64_repeated)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
MSG_T::int64_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.T.int64_repeated)
  return int64_repeated_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
MSG_T::mutable_int64_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.T.int64_repeated)
  return &int64_repeated_;
}

// optional string string_optional = 10;
inline bool MSG_T::has_string_optional() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void MSG_T::set_has_string_optional() {
  _has_bits_[0] |= 0x00000200u;
}
inline void MSG_T::clear_has_string_optional() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void MSG_T::clear_string_optional() {
  if (string_optional_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_->clear();
  }
  clear_has_string_optional();
}
inline const ::std::string& MSG_T::string_optional() const {
  // @@protoc_insertion_point(field_get:MSG.T.string_optional)
  return *string_optional_;
}
inline void MSG_T::set_string_optional(const ::std::string& value) {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  string_optional_->assign(value);
  // @@protoc_insertion_point(field_set:MSG.T.string_optional)
}
inline void MSG_T::set_string_optional(const char* value) {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  string_optional_->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG.T.string_optional)
}
inline void MSG_T::set_string_optional(const char* value, size_t size) {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  string_optional_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG.T.string_optional)
}
inline ::std::string* MSG_T::mutable_string_optional() {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MSG.T.string_optional)
  return string_optional_;
}
inline ::std::string* MSG_T::release_string_optional() {
  clear_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = string_optional_;
    string_optional_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MSG_T::set_allocated_string_optional(::std::string* string_optional) {
  if (string_optional_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete string_optional_;
  }
  if (string_optional) {
    set_has_string_optional();
    string_optional_ = string_optional;
  } else {
    clear_has_string_optional();
    string_optional_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.T.string_optional)
}

// required string string_required = 11;
inline bool MSG_T::has_string_required() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void MSG_T::set_has_string_required() {
  _has_bits_[0] |= 0x00000400u;
}
inline void MSG_T::clear_has_string_required() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void MSG_T::clear_string_required() {
  if (string_required_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_->clear();
  }
  clear_has_string_required();
}
inline const ::std::string& MSG_T::string_required() const {
  // @@protoc_insertion_point(field_get:MSG.T.string_required)
  return *string_required_;
}
inline void MSG_T::set_string_required(const ::std::string& value) {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  string_required_->assign(value);
  // @@protoc_insertion_point(field_set:MSG.T.string_required)
}
inline void MSG_T::set_string_required(const char* value) {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  string_required_->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG.T.string_required)
}
inline void MSG_T::set_string_required(const char* value, size_t size) {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  string_required_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG.T.string_required)
}
inline ::std::string* MSG_T::mutable_string_required() {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MSG.T.string_required)
  return string_required_;
}
inline ::std::string* MSG_T::release_string_required() {
  clear_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = string_required_;
    string_required_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MSG_T::set_allocated_string_required(::std::string* string_required) {
  if (string_required_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete string_required_;
  }
  if (string_required) {
    set_has_string_required();
    string_required_ = string_required;
  } else {
    clear_has_string_required();
    string_required_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.T.string_required)
}

// repeated string string_repeated = 12;
inline int MSG_T::string_repeated_size() const {
  return string_repeated_.size();
}
inline void MSG_T::clear_string_repeated() {
  string_repeated_.Clear();
}
inline const ::std::string& MSG_T::string_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.T.string_repeated)
  return string_repeated_.Get(index);
}
inline ::std::string* MSG_T::mutable_string_repeated(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.T.string_repeated)
  return string_repeated_.Mutable(index);
}
inline void MSG_T::set_string_repeated(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MSG.T.string_repeated)
  string_repeated_.Mutable(index)->assign(value);
}
inline void MSG_T::set_string_repeated(int index, const char* value) {
  string_repeated_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG.T.string_repeated)
}
inline void MSG_T::set_string_repeated(int index, const char* value, size_t size) {
  string_repeated_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG.T.string_repeated)
}
inline ::std::string* MSG_T::add_string_repeated() {
  return string_repeated_.Add();
}
inline void MSG_T::add_string_repeated(const ::std::string& value) {
  string_repeated_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MSG.T.string_repeated)
}
inline void MSG_T::add_string_repeated(const char* value) {
  string_repeated_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MSG.T.string_repeated)
}
inline void MSG_T::add_string_repeated(const char* value, size_t size) {
  string_repeated_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MSG.T.string_repeated)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MSG_T::string_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.T.string_repeated)
  return string_repeated_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MSG_T::mutable_string_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.T.string_repeated)
  return &string_repeated_;
}

// -------------------------------------------------------------------

// MSG

// optional bool bool_optional = 1;
inline bool MSG::has_bool_optional() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG::set_has_bool_optional() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG::clear_has_bool_optional() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG::clear_bool_optional() {
  bool_optional_ = false;
  clear_has_bool_optional();
}
inline bool MSG::bool_optional() const {
  // @@protoc_insertion_point(field_get:MSG.bool_optional)
  return bool_optional_;
}
inline void MSG::set_bool_optional(bool value) {
  set_has_bool_optional();
  bool_optional_ = value;
  // @@protoc_insertion_point(field_set:MSG.bool_optional)
}

// required bool bool_required = 2;
inline bool MSG::has_bool_required() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG::set_has_bool_required() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG::clear_has_bool_required() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG::clear_bool_required() {
  bool_required_ = false;
  clear_has_bool_required();
}
inline bool MSG::bool_required() const {
  // @@protoc_insertion_point(field_get:MSG.bool_required)
  return bool_required_;
}
inline void MSG::set_bool_required(bool value) {
  set_has_bool_required();
  bool_required_ = value;
  // @@protoc_insertion_point(field_set:MSG.bool_required)
}

// repeated bool bool_repeated = 3;
inline int MSG::bool_repeated_size() const {
  return bool_repeated_.size();
}
inline void MSG::clear_bool_repeated() {
  bool_repeated_.Clear();
}
inline bool MSG::bool_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.bool_repeated)
  return bool_repeated_.Get(index);
}
inline void MSG::set_bool_repeated(int index, bool value) {
  bool_repeated_.Set(index, value);
  // @@protoc_insertion_point(field_set:MSG.bool_repeated)
}
inline void MSG::add_bool_repeated(bool value) {
  bool_repeated_.Add(value);
  // @@protoc_insertion_point(field_add:MSG.bool_repeated)
}
inline const ::google::protobuf::RepeatedField< bool >&
MSG::bool_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.bool_repeated)
  return bool_repeated_;
}
inline ::google::protobuf::RepeatedField< bool >*
MSG::mutable_bool_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.bool_repeated)
  return &bool_repeated_;
}

// optional int32 int_optional = 4;
inline bool MSG::has_int_optional() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MSG::set_has_int_optional() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MSG::clear_has_int_optional() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MSG::clear_int_optional() {
  int_optional_ = 0;
  clear_has_int_optional();
}
inline ::google::protobuf::int32 MSG::int_optional() const {
  // @@protoc_insertion_point(field_get:MSG.int_optional)
  return int_optional_;
}
inline void MSG::set_int_optional(::google::protobuf::int32 value) {
  set_has_int_optional();
  int_optional_ = value;
  // @@protoc_insertion_point(field_set:MSG.int_optional)
}

// required int32 int_required = 5;
inline bool MSG::has_int_required() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MSG::set_has_int_required() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MSG::clear_has_int_required() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MSG::clear_int_required() {
  int_required_ = 0;
  clear_has_int_required();
}
inline ::google::protobuf::int32 MSG::int_required() const {
  // @@protoc_insertion_point(field_get:MSG.int_required)
  return int_required_;
}
inline void MSG::set_int_required(::google::protobuf::int32 value) {
  set_has_int_required();
  int_required_ = value;
  // @@protoc_insertion_point(field_set:MSG.int_required)
}

// repeated int32 int_repeated = 6;
inline int MSG::int_repeated_size() const {
  return int_repeated_.size();
}
inline void MSG::clear_int_repeated() {
  int_repeated_.Clear();
}
inline ::google::protobuf::int32 MSG::int_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.int_repeated)
  return int_repeated_.Get(index);
}
inline void MSG::set_int_repeated(int index, ::google::protobuf::int32 value) {
  int_repeated_.Set(index, value);
  // @@protoc_insertion_point(field_set:MSG.int_repeated)
}
inline void MSG::add_int_repeated(::google::protobuf::int32 value) {
  int_repeated_.Add(value);
  // @@protoc_insertion_point(field_add:MSG.int_repeated)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MSG::int_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.int_repeated)
  return int_repeated_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MSG::mutable_int_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.int_repeated)
  return &int_repeated_;
}

// optional int64 int64_optional = 7;
inline bool MSG::has_int64_optional() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MSG::set_has_int64_optional() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MSG::clear_has_int64_optional() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MSG::clear_int64_optional() {
  int64_optional_ = GOOGLE_LONGLONG(0);
  clear_has_int64_optional();
}
inline ::google::protobuf::int64 MSG::int64_optional() const {
  // @@protoc_insertion_point(field_get:MSG.int64_optional)
  return int64_optional_;
}
inline void MSG::set_int64_optional(::google::protobuf::int64 value) {
  set_has_int64_optional();
  int64_optional_ = value;
  // @@protoc_insertion_point(field_set:MSG.int64_optional)
}

// required int64 int64_required = 8;
inline bool MSG::has_int64_required() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MSG::set_has_int64_required() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MSG::clear_has_int64_required() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MSG::clear_int64_required() {
  int64_required_ = GOOGLE_LONGLONG(0);
  clear_has_int64_required();
}
inline ::google::protobuf::int64 MSG::int64_required() const {
  // @@protoc_insertion_point(field_get:MSG.int64_required)
  return int64_required_;
}
inline void MSG::set_int64_required(::google::protobuf::int64 value) {
  set_has_int64_required();
  int64_required_ = value;
  // @@protoc_insertion_point(field_set:MSG.int64_required)
}

// repeated int64 int64_repeated = 9;
inline int MSG::int64_repeated_size() const {
  return int64_repeated_.size();
}
inline void MSG::clear_int64_repeated() {
  int64_repeated_.Clear();
}
inline ::google::protobuf::int64 MSG::int64_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.int64_repeated)
  return int64_repeated_.Get(index);
}
inline void MSG::set_int64_repeated(int index, ::google::protobuf::int64 value) {
  int64_repeated_.Set(index, value);
  // @@protoc_insertion_point(field_set:MSG.int64_repeated)
}
inline void MSG::add_int64_repeated(::google::protobuf::int64 value) {
  int64_repeated_.Add(value);
  // @@protoc_insertion_point(field_add:MSG.int64_repeated)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
MSG::int64_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.int64_repeated)
  return int64_repeated_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
MSG::mutable_int64_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.int64_repeated)
  return &int64_repeated_;
}

// optional string string_optional = 10;
inline bool MSG::has_string_optional() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void MSG::set_has_string_optional() {
  _has_bits_[0] |= 0x00000200u;
}
inline void MSG::clear_has_string_optional() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void MSG::clear_string_optional() {
  if (string_optional_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_->clear();
  }
  clear_has_string_optional();
}
inline const ::std::string& MSG::string_optional() const {
  // @@protoc_insertion_point(field_get:MSG.string_optional)
  return *string_optional_;
}
inline void MSG::set_string_optional(const ::std::string& value) {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  string_optional_->assign(value);
  // @@protoc_insertion_point(field_set:MSG.string_optional)
}
inline void MSG::set_string_optional(const char* value) {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  string_optional_->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG.string_optional)
}
inline void MSG::set_string_optional(const char* value, size_t size) {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  string_optional_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG.string_optional)
}
inline ::std::string* MSG::mutable_string_optional() {
  set_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_optional_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MSG.string_optional)
  return string_optional_;
}
inline ::std::string* MSG::release_string_optional() {
  clear_has_string_optional();
  if (string_optional_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = string_optional_;
    string_optional_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MSG::set_allocated_string_optional(::std::string* string_optional) {
  if (string_optional_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete string_optional_;
  }
  if (string_optional) {
    set_has_string_optional();
    string_optional_ = string_optional;
  } else {
    clear_has_string_optional();
    string_optional_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.string_optional)
}

// required string string_required = 11;
inline bool MSG::has_string_required() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void MSG::set_has_string_required() {
  _has_bits_[0] |= 0x00000400u;
}
inline void MSG::clear_has_string_required() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void MSG::clear_string_required() {
  if (string_required_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_->clear();
  }
  clear_has_string_required();
}
inline const ::std::string& MSG::string_required() const {
  // @@protoc_insertion_point(field_get:MSG.string_required)
  return *string_required_;
}
inline void MSG::set_string_required(const ::std::string& value) {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  string_required_->assign(value);
  // @@protoc_insertion_point(field_set:MSG.string_required)
}
inline void MSG::set_string_required(const char* value) {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  string_required_->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG.string_required)
}
inline void MSG::set_string_required(const char* value, size_t size) {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  string_required_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG.string_required)
}
inline ::std::string* MSG::mutable_string_required() {
  set_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_required_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MSG.string_required)
  return string_required_;
}
inline ::std::string* MSG::release_string_required() {
  clear_has_string_required();
  if (string_required_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = string_required_;
    string_required_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MSG::set_allocated_string_required(::std::string* string_required) {
  if (string_required_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete string_required_;
  }
  if (string_required) {
    set_has_string_required();
    string_required_ = string_required;
  } else {
    clear_has_string_required();
    string_required_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.string_required)
}

// repeated string string_repeated = 12;
inline int MSG::string_repeated_size() const {
  return string_repeated_.size();
}
inline void MSG::clear_string_repeated() {
  string_repeated_.Clear();
}
inline const ::std::string& MSG::string_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.string_repeated)
  return string_repeated_.Get(index);
}
inline ::std::string* MSG::mutable_string_repeated(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.string_repeated)
  return string_repeated_.Mutable(index);
}
inline void MSG::set_string_repeated(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MSG.string_repeated)
  string_repeated_.Mutable(index)->assign(value);
}
inline void MSG::set_string_repeated(int index, const char* value) {
  string_repeated_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG.string_repeated)
}
inline void MSG::set_string_repeated(int index, const char* value, size_t size) {
  string_repeated_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG.string_repeated)
}
inline ::std::string* MSG::add_string_repeated() {
  return string_repeated_.Add();
}
inline void MSG::add_string_repeated(const ::std::string& value) {
  string_repeated_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MSG.string_repeated)
}
inline void MSG::add_string_repeated(const char* value) {
  string_repeated_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MSG.string_repeated)
}
inline void MSG::add_string_repeated(const char* value, size_t size) {
  string_repeated_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MSG.string_repeated)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MSG::string_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.string_repeated)
  return string_repeated_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MSG::mutable_string_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.string_repeated)
  return &string_repeated_;
}

// optional .MSG.T T_optional = 13;
inline bool MSG::has_t_optional() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void MSG::set_has_t_optional() {
  _has_bits_[0] |= 0x00001000u;
}
inline void MSG::clear_has_t_optional() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void MSG::clear_t_optional() {
  if (t_optional_ != NULL) t_optional_->::MSG_T::Clear();
  clear_has_t_optional();
}
inline const ::MSG_T& MSG::t_optional() const {
  // @@protoc_insertion_point(field_get:MSG.T_optional)
  return t_optional_ != NULL ? *t_optional_ : *default_instance_->t_optional_;
}
inline ::MSG_T* MSG::mutable_t_optional() {
  set_has_t_optional();
  if (t_optional_ == NULL) t_optional_ = new ::MSG_T;
  // @@protoc_insertion_point(field_mutable:MSG.T_optional)
  return t_optional_;
}
inline ::MSG_T* MSG::release_t_optional() {
  clear_has_t_optional();
  ::MSG_T* temp = t_optional_;
  t_optional_ = NULL;
  return temp;
}
inline void MSG::set_allocated_t_optional(::MSG_T* t_optional) {
  delete t_optional_;
  t_optional_ = t_optional;
  if (t_optional) {
    set_has_t_optional();
  } else {
    clear_has_t_optional();
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.T_optional)
}

// required .MSG.T T_required = 14;
inline bool MSG::has_t_required() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void MSG::set_has_t_required() {
  _has_bits_[0] |= 0x00002000u;
}
inline void MSG::clear_has_t_required() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void MSG::clear_t_required() {
  if (t_required_ != NULL) t_required_->::MSG_T::Clear();
  clear_has_t_required();
}
inline const ::MSG_T& MSG::t_required() const {
  // @@protoc_insertion_point(field_get:MSG.T_required)
  return t_required_ != NULL ? *t_required_ : *default_instance_->t_required_;
}
inline ::MSG_T* MSG::mutable_t_required() {
  set_has_t_required();
  if (t_required_ == NULL) t_required_ = new ::MSG_T;
  // @@protoc_insertion_point(field_mutable:MSG.T_required)
  return t_required_;
}
inline ::MSG_T* MSG::release_t_required() {
  clear_has_t_required();
  ::MSG_T* temp = t_required_;
  t_required_ = NULL;
  return temp;
}
inline void MSG::set_allocated_t_required(::MSG_T* t_required) {
  delete t_required_;
  t_required_ = t_required;
  if (t_required) {
    set_has_t_required();
  } else {
    clear_has_t_required();
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.T_required)
}

// repeated .MSG.T T_repeated = 15;
inline int MSG::t_repeated_size() const {
  return t_repeated_.size();
}
inline void MSG::clear_t_repeated() {
  t_repeated_.Clear();
}
inline const ::MSG_T& MSG::t_repeated(int index) const {
  // @@protoc_insertion_point(field_get:MSG.T_repeated)
  return t_repeated_.Get(index);
}
inline ::MSG_T* MSG::mutable_t_repeated(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.T_repeated)
  return t_repeated_.Mutable(index);
}
inline ::MSG_T* MSG::add_t_repeated() {
  // @@protoc_insertion_point(field_add:MSG.T_repeated)
  return t_repeated_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG_T >&
MSG::t_repeated() const {
  // @@protoc_insertion_point(field_list:MSG.T_repeated)
  return t_repeated_;
}
inline ::google::protobuf::RepeatedPtrField< ::MSG_T >*
MSG::mutable_t_repeated() {
  // @@protoc_insertion_point(field_mutable_list:MSG.T_repeated)
  return &t_repeated_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2eproto__INCLUDED
